### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by geekymsk** [howtographql/react-apollo#36]
when I run "yarn dev"
it gives me this error

 ...req,
    ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
error An unexpected error occurred: "Command failed.
Exit code: 1

the error is located in server/src/index.js:19

I am not able to start the server.

**Comment by geekymsk** [comment]
sorry, my bad.
it was the issue with my node version. I have upgraded it to latest and issue is gone.
