### ISSUE TITLE
[GraphQL error]: Message: Cannot query field 'links' on type 'Query'. (line 2, column 3):

### ISSUE THREAD

**Issue by kryton** [howtographql/react-apollo#63]
Hi.
I'm following the tutorial on https://www.howtographql.com/react-apollo/1-getting-started/ 
have followed all of the steps, (which basically involves downloading the starter tarball and running the yarn install commands).

when I try to execute the feed query on the playground, it gives me the following error in the console.

`
$ graphql playground
Type "Node" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Server is running on http://localhost:4000
Serving playground at http://localhost:3000/playground
Request to http://localhost:4466:
query:
{
  links {
    id
    createdAt
    description
    url
  }
}
operationName: null
variables:
{}
[GraphQL error]: Message: Cannot query field 'links' on type 'Query'. (line 2, column 3):
  links {
  ^, Location: [object Object], Path: undefined
[Network error]: Error: Cannot query field 'links' on type 'Query'. (line 2, column 3):
  links {
  ^
Error: Cannot query field 'links' on type 'Query'. (line 2, column 3):
  links {
  ^
    at BatchedGraphQLClient.<anonymous> (C:\Users\ihols\src\hackernews-react-apollo\server\node_modules\http-link-dataloader\dist\src\BatchedGraphQLClient.js:77:35)
    at step (C:\Users\ihols\src\hackernews-react-apollo\server\node_modules\http-link-dataloader\dist\src\BatchedGraphQLClient.js:40:23)
    at Object.next (C:\Users\ihols\src\hackernews-react-apollo\server\node_modules\http-link-dataloader\dist\src\BatchedGraphQLClient.js:21:53)
    at fulfilled (C:\Users\ihols\src\hackernews-react-apollo\server\node_modules\http-link-dataloader\dist\src\BatchedGraphQLClient.js:12:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
`

DB is mysql in docker container.
OS is windows 10.
Thanks!

**Comment by kryton** [comment]
digging into this. there was an issue when I deployed the DB. it didn't create all the tables, and referenced a 'datamodel.prisma' which only had a user table in there (no idea where this came from).
when I updated that file to have the same contents as database/datamodel.graphql it passed.
