### ISSUE TITLE
Getting error while running yarn prisma deploy

### ISSUE THREAD

**Issue by e-belair** [howtographql/react-apollo#84]
Hi I'm encountering the following error while running yarn prisma install
```
# xxxx @ xxxx-ThinkPad-X230 in ~/www/tutos/hackernews-react-apollo/server on git:master x [11:42:48] 
$ yarn prisma deploy
yarn run v1.17.3
$ prisma deploy
? Set up a new Prisma server or deploy to an existing server? Demo server + MySQL database
? Choose the region of your demo server xxxxxxxxxxxxxxx-d77b97/demo-eu1
? Choose a name for your service server
? Choose a name for your stage dev

Written endpoint `https://eu1.prisma.sh/xxxxxxxxxxxxxxx-d77b97/server/dev` to prisma.yml

Deploying service `server` to stage `dev` to server `prisma-eu1` 368ms
Service is already up to date.

post-deploy:
 ▸    Cannot use GraphQLNonNull "LinkWhereUniqueInput!" from another module or
 ▸    realm.
 ▸    
 ▸    Ensure that there is only one instance of "graphql" in the node_modules
 ▸    directory. If different versions of "graphql" are the dependencies of
 ▸    other
 ▸    relied on modules, use "resolutions" to ensure only one version is
 ▸    installed.
 ▸    
 ▸    https://yarnpkg.com/en/docs/selective-version-resolutions
 ▸    
 ▸    Duplicate "graphql" modules cannot be used at the same time since
 ▸    different
 ▸    versions may have different capabilities and behavior. The data from one
 ▸    version used in the function from another could produce confusing and
 ▸    spurious results.

Get in touch if you need help: https://spectrum.chat/prisma
To get more detailed output, run $ export DEBUG="*"

Running prisma generate...

Generating schema... 52ms
Running prisma generate ✖
Done in 16.93s.

# xxxx @ xxxx-ThinkPad-X230 in ~/www/tutos/hackernews-react-apollo/server on git:master x [11:43:14] 
$ yarn start
yarn run v1.17.3
$ node src/index.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::4000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at /home/xxxx/www/tutos/hackernews-react-apollo/server/node_modules/graphql-yoga/dist/index.js:344:28
    at new Promise (<anonymous>)
    at GraphQLServer.start (/home/xxxx/www/tutos/hackernews-react-apollo/server/node_modules/graphql-yoga/dist/index.js:342:16)
    at Object.<anonymous> (/home/xxxx/www/tutos/hackernews-react-apollo/server/src/index.js:27:8)
    at Module._compile (module.js:652:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ntt2k** [comment]
I confirmed this error. I see this as well!

**Comment by ntt2k** [comment]
this is a solution, remove yarn.lock and do yarn install again -->

https://github.com/howtographql/react-apollo/issues/33

**Comment by kevb10** [comment]
This solves the issue

**Comment by EdwardGoomba** [comment]
Solved it for me too. Can we close this?

**Comment by fichorka** [comment]
`yarn prisma deploy` doesn't work for me: `deploy is not a prisma command.`
